### ISSUE TITLE
GitHub doesn't support plugins

### ISSUE THREAD

**Issue by AndrewJack** [BSkyB/bskyb.github.io#16]
https://help.github.com/articles/page-build-failed-unknown-tag-error/

Received this error when merging #15 

@dapacheco

**Comment by AndrewJack** [comment]
Should probably move to the same approach as http://developers.sky.com/vacancies/

**Comment by dapacheco** [comment]
@AndrewJack I'll convert it to use a loop as per vacancies.

**Comment by AndrewJack** [comment]
fixed in #18
